---
title: "Pinwheels Baby Preprocessing"
author: "Felicia Zhang"
date: '2017-08-23'
output: html_document
---

```{r}
library(ggplot2) 
library(zoo)
library(reshape)
library(plyr)
library(scales) 
library(data.table)
library(signal)
library(matrixStats)
library(lme4)
library(arm)
library(wesanderson)

#import pilot data (n=10)
#raw <- read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/Pinwheels14/Pinwheels14_1-10.csv")
raw2 <- read.csv("/Volumes/emberson/ResearchProjects/Pupillometry/Pinwheels14/Pinwheels14_11-17.csv")
```

```{r}
#1. Make a copy of original and some class conversions
poo <- subset(raw2, TRIAL_INDEX < 49) #48 trials (3*16)

poo$RIGHT_PUPIL_SIZE <- as.numeric(as.character(poo$RIGHT_PUPIL_SIZE))
poo$RIGHT_GAZE_X <- as.numeric(as.character(poo$RIGHT_GAZE_X))
poo$RIGHT_GAZE_Y <- as.numeric(as.character(poo$RIGHT_GAZE_Y))
summary(poo)

#the warnings appear bc of converting . to NA, which is correct
length(which(raw2$RIGHT_PUPIL_SIZE=="."))
length(which(is.na(poo$RIGHT_PUPIL_SIZE)))

#2. Assigning each subject a number for subID so it's easier to index 
poo$subID <- 0
subs <- unique(poo$RECORDING_SESSION_LABEL)

for (i in 1:length(subs)){
  poo$subID[poo$RECORDING_SESSION_LABEL == subs[i]] <- i+10  
}

#3. Standardize time 
subs <- unique(poo$subID)

for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID == subs[j]])
  print(subs[j])
  for (i in 1:length(trials)) {
    #gets the timestamp for a trial for a subject
    times = poo$TIMESTAMP[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] 
    start = min(times) #finds the smallest timestamp
    poo$TIMECODE[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] = poo$TIMESTAMP[poo$subID == subs[j] & poo$TRIAL_INDEX == trials[i]] - start
  }}

#4. Check hertz recorded at 
for (i in 1:length(unique(poo$subID))) {
blah <- subset(poo, subID == subs[i])
print(i)
print(head(blah$TIMECODE))
}
# Conclusion: All were recorded at 500 Hz

# Data reduction, changing 500 Hz to 250 Hz
i <- max(poo$TIMECODE)
ii <- seq(2, i, by=4 )
poo <- poo[ !poo$TIMECODE %in% ii, ]

# Double check it's at 250 Hz
for (i in 1:length(unique(poo$subID))) {
blah <- subset(poo, subID == subs[i])
print(i)
print(head(blah$TIMECODE))
}

#5. Fill in gaps of blinks
#The duration of a blink is on average 100-150 milliseconds according to UCL researcher (conservative)
#between 100-400ms according to the Harvard Database of Useful Biological Numbers (liberal)

#converts data.frame to data.table, faster to manipulate with large data
poo <- data.table(poo) 
#creates column called 'orig' with row index
poo <- poo[, orig := .I] 

#create empty DF
yoo <- data.frame(RECORDING_SESSION_LABEL= character(), HTARGET_DISTANCE= numeric(),HTARGET_X= numeric(),HTARGET_Y= numeric(),LEFT_GAZE_X= numeric(),LEFT_GAZE_Y= numeric(),LEFT_IN_BLINK= numeric(),LEFT_PUPIL_SIZE= numeric(),RIGHT_GAZE_X= numeric(),RIGHT_GAZE_Y= numeric(),RIGHT_IN_BLINK= numeric(),RIGHT_PUPIL_SIZE= numeric(),SAMPLE_INDEX= numeric(),SAMPLE_MESSAGE= character(),TARGET_X= numeric(),TARGET_Y= numeric(),TIMESTAMP= numeric(),TRIAL_INDEX= numeric(),targetside= numeric(),subID= numeric(),TIMECODE= numeric(),orig= numeric(),rleLength= numeric())

#for each subject, create column called rleLength that counts consecutive filled or NA values (to figure out how long NA values are)
for (i in 1:length(subs)) { 
  poo2 <- subset(poo, subID==subs[i])
  poo2 <- poo2[, rleLength := {rr <- rle(is.na(poo2$RIGHT_PUPIL_SIZE)); rep(rr$length, rr$length)}]
  #create column rleLength that counts consecutive filled or NA values (figure out how long NA values are)
  yoo <- rbind(yoo,poo2)
}

#copy to poo DF
poo <- yoo

#Only fill in NA gaps with length < 100 (100 samples = 400ms) going liberal, using linear interpolation na.approx. If you want cubic spline interpolation, use na.spline
poo$RIGHT_PUPIL_SIZE <- with(poo, ifelse(rleLength < 100, na.approx(RIGHT_PUPIL_SIZE), RIGHT_PUPIL_SIZE))
summary(poo$RIGHT_PUPIL_SIZE) 
#RESULT = 30.3% blank

#7. Convert pupil area to diameter for certain participants 
# diameter = 256 * sqrt(area / Pi)
diameter <- function (x) {
  256*sqrt(x/pi)
}
subs <- unique(poo$subID)
for (i in 1:length(subs)){
  summary(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[i]])
  a <- summary(poo$RIGHT_PUPIL_SIZE[poo$subID==subs[i]])
  if (a[4] < 1000){ #meaning it's recorded in area
    start <- min(which(poo$subID==subs[i])) #find start of that participant
    end <- max(which(poo$subID==subs[i])) #find end of that participant
    poo$RIGHT_PUPIL_SIZE[start:end] <- sapply(poo$RIGHT_PUPIL_SIZE[start:end],diameter) 
  }}

#8. Standardize pupil size (percentage change from baseline)
poo$SAMPLE_MESSAGE <- as.character(poo$SAMPLE_MESSAGE)

#Task:
#250ms blank
#1500ms circle
#800ms blank
#1000ms target

#baseline = 1750ms of a trial or 437 samples (USE THIS)
pooA <- poo

subs <- unique(pooA$subID)
for (j in 1:length(subs)) {
  trials <- unique(pooA$TRIAL_INDEX[pooA$subID==subs[j]])
  print(subs[j])
  for (i in 1:length(trials)) {
    bluecircle <- min(which(pooA$subID==subs[j] & pooA$TRIAL_INDEX == trials[i]))
    baselineall <- pooA$RIGHT_PUPIL_SIZE[bluecircle:(bluecircle+436)] 
    baseline <- mean(baselineall,na.rm = TRUE) #baseline avg
    pooA$PUPIL_CORRECTED[pooA$subID==subs[j] & pooA$TRIAL_INDEX == trials[i]] <- (pooA$RIGHT_PUPIL_SIZE[pooA$subID==subs[j] & pooA$TRIAL_INDEX == trials[i]] - baseline) / baseline
  }}

poo <- pooA

#10. Add in additional information related to experiment
#add which side of screen they're looking at 
#1,3,5 = L, 2,4,6 = R
poo$leftright <- 0
poo$leftright[poo$targetside==1|poo$targetside==3|poo$targetside==5] <- 1 #left
poo$leftright[poo$targetside==2|poo$targetside==4|poo$targetside==6] <- 2 #right

#labelling 1 - 2 for sides
#1 = pre switch, 2 = post switch
poo$switch <- 0
poo$switch[poo$TRIAL_INDEX < 9] <- 1
poo$switch[poo$TRIAL_INDEX > 8 & poo$TRIAL_INDEX < 17] <- 2
poo$switch[poo$TRIAL_INDEX > 16 & poo$TRIAL_INDEX < 25] <- 1
poo$switch[poo$TRIAL_INDEX > 24 & poo$TRIAL_INDEX < 33] <- 2
poo$switch[poo$TRIAL_INDEX > 32 & poo$TRIAL_INDEX < 41] <- 1
poo$switch[poo$TRIAL_INDEX > 40] <- 2

#labelling 1 - 6 for sides
poo$sub.blocks <- 0
poo$sub.blocks[poo$TRIAL_INDEX < 9] <- 1
poo$sub.blocks[poo$TRIAL_INDEX > 8 & poo$TRIAL_INDEX < 17] <- 2
poo$sub.blocks[poo$TRIAL_INDEX > 16 & poo$TRIAL_INDEX < 25] <- 3
poo$sub.blocks[poo$TRIAL_INDEX > 24 & poo$TRIAL_INDEX < 33] <- 4
poo$sub.blocks[poo$TRIAL_INDEX > 32 & poo$TRIAL_INDEX < 41] <- 5
poo$sub.blocks[poo$TRIAL_INDEX > 40] <- 6

#labelling 1 - 3 for blocks
poo$block <- 0
poo$block[poo$TRIAL_INDEX < 17] <- 1
poo$block[poo$TRIAL_INDEX > 16 & poo$TRIAL_INDEX < 33] <- 2
poo$block[poo$TRIAL_INDEX > 32] <- 3   

#recode trial number
poo$trialnum <- 0
poo$trialnum[poo$TRIAL_INDEX == 1 | poo$TRIAL_INDEX == 9 | poo$TRIAL_INDEX == 17 | poo$TRIAL_INDEX == 25 | poo$TRIAL_INDEX == 33 | poo$TRIAL_INDEX == 41] <- 1
poo$trialnum[poo$TRIAL_INDEX == 2 | poo$TRIAL_INDEX == 10 | poo$TRIAL_INDEX == 18 | poo$TRIAL_INDEX == 26 | poo$TRIAL_INDEX == 34 | poo$TRIAL_INDEX == 42] <- 2
poo$trialnum[poo$TRIAL_INDEX == 3 | poo$TRIAL_INDEX == 11 | poo$TRIAL_INDEX == 19 | poo$TRIAL_INDEX == 27 | poo$TRIAL_INDEX == 35 | poo$TRIAL_INDEX == 43] <- 3
poo$trialnum[poo$TRIAL_INDEX == 4 | poo$TRIAL_INDEX == 12 | poo$TRIAL_INDEX == 20 | poo$TRIAL_INDEX == 28 | poo$TRIAL_INDEX == 36 | poo$TRIAL_INDEX == 44] <- 4
poo$trialnum[poo$TRIAL_INDEX == 5 | poo$TRIAL_INDEX == 13 | poo$TRIAL_INDEX == 21 | poo$TRIAL_INDEX == 29 | poo$TRIAL_INDEX == 37 | poo$TRIAL_INDEX == 45] <- 5
poo$trialnum[poo$TRIAL_INDEX == 6 | poo$TRIAL_INDEX == 14 | poo$TRIAL_INDEX == 22 | poo$TRIAL_INDEX == 30 | poo$TRIAL_INDEX == 38 | poo$TRIAL_INDEX == 46] <- 6
poo$trialnum[poo$TRIAL_INDEX == 7 | poo$TRIAL_INDEX == 15 | poo$TRIAL_INDEX == 23 | poo$TRIAL_INDEX == 31 | poo$TRIAL_INDEX == 39 | poo$TRIAL_INDEX == 47] <- 7
poo$trialnum[poo$TRIAL_INDEX == 8 | poo$TRIAL_INDEX == 16 | poo$TRIAL_INDEX == 24 | poo$TRIAL_INDEX == 32 | poo$TRIAL_INDEX == 40 | poo$TRIAL_INDEX == 48] <- 8
```

```{r}
#for each subject, each trial, calculate percent trackloss (include NA and gazes that are off screen)
#1 = looking at target
#0 = not looking at target
#9 = invalid looking (i.e. not even on the )

#width is 1280
targetx1 <- 426
targetx2 <- 854
poo$trackloss <- 99
poo$lookattarget <- 9

subs <- unique(poo$subID)
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==subs[j]])
  print(subs[j])
  for (i in 1:length(trials)) {
  #gets all sample for 1 trial  
  woo <- subset(poo, subID==subs[j] & TRIAL_INDEX == trials[i])
  a1 <- which(is.na(woo$RIGHT_GAZE_X)) #NA values
  a2 <- which(woo$RIGHT_GAZE_X < 0) #looking off screen
  a3 <- which(woo$RIGHT_GAZE_Y < 0) #looking off screen
  a4 <- which(woo$RIGHT_GAZE_X > 1280) #looking off screen
  a5 <- which(woo$RIGHT_GAZE_Y > 1024) #looking off screen
  a <- length(a1)+length(a2)+length(a3)+length(a4)+length(a5) #num of samples that are bad
  trackloss <- a/length(woo$RECORDING_SESSION_LABEL)
  z <- min(which(poo$subID==subs[j] & poo$TRIAL_INDEX== trials[i])) #when that trial starts
  zz <- max(which(poo$subID==subs[j] & poo$TRIAL_INDEX== trials[i])) #when that trial ends
  poo$trackloss[z:zz] <- trackloss #add info to main DF
  }
  }

# only keep trials less than 50% trackloss
poo2 <- subset(poo, trackloss < .50) 

# for the remaining trials remove trackloss
a <- which(is.na(poo2$RIGHT_GAZE_X)) #X and Y are the same
poo3 <- poo2[-c(a), ]

# remove gazes that are off the screen (screen dimensions of screen are 1280 x 1024)
a <- which(poo3$RIGHT_GAZE_X < 0)
poo3 <- poo3[-c(a), ]
a <- which(poo3$RIGHT_GAZE_X > 1280)
poo3 <- poo3[-c(a), ]

## now code for every single sample calculate if they're looking at target
targetx1 <- 426
targetx2 <- 854

#0 = distractor, 1 = target, 5 = center, 
for (i in 1:length(poo3$RECORDING_SESSION_LABEL)) {
side <- poo3$leftright[i] #1==left, 2==right
gaze <- poo3$RIGHT_GAZE_X[i]
if (side==1) { #if target is on the left side
  if (poo3$RIGHT_GAZE_X[i] < targetx1) { #if gaze is on the left side
    poo3$lookattarget[i] <- 1 #1 = looking at target location
  } else if (poo3$RIGHT_GAZE_X[i] > targetx2) {
    poo3$lookattarget[i] <- 0 #0 = looking at distractor
  } else {
    poo3$lookattarget[i] <- 5 #5 = must be looking at center
  }
} 
if (side==2) { #if target is on the right side
  if (poo3$RIGHT_GAZE_X[i] > targetx2) { #if gaze is on the right side
    poo3$lookattarget[i] <- 1 #1 = looking at target location
  } else if (poo3$RIGHT_GAZE_X[i] < targetx1 ) { 
    poo3$lookattarget[i] <- 0 #0 = looking at distractor
  } else {
    poo3$lookattarget[i] <- 5 #5 = must be looking at center
  }
}
}

#replace infinite with NA
is.na(poo3$PUPIL_CORRECTED) <- sapply(poo3$PUPIL_CORRECTED, is.infinite)

#scatterplot of pupil size per subject
pupil.sub <- ddply(poo3,.(subID,TRIAL_INDEX),summarise,pupilsize=mean(PUPIL_CORRECTED,na.rm = TRUE))

ggplot(pupil.sub,aes(x=factor(subID),y=pupilsize,fill=factor(TRIAL_INDEX),color=factor(TRIAL_INDEX)))+
  theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line = element_line(colour = "black"))+
  geom_point()+ggtitle("Pupil change per subject (no filter)")+
  labs(x = "Subject", y = "Pupil change (%)")+
  theme(plot.title = element_text(face="bold", size=20, hjust=0))+
  theme(axis.title = element_text(face="bold", size=20))+ 
  theme(axis.text.x  = element_text(size=20),axis.text.y  = element_text(size=20))+
  theme(legend.text=element_text(size=16),legend.title=element_text(size=16))+
  theme(legend.position="none")+
  scale_y_continuous(labels=percent,limits=c(-0.6,1.5),breaks=seq(-0.6,1.5,0.5))

write.csv(poo, "Pinwheel14_11-17_Infant_Preprocessed_AllSamples.csv", row.names=TRUE) #save to 
write.csv(poo3, "Pinwheel14_11-17_Infant_Preprocessed_RemovedTrackloss.csv", row.names=TRUE) #save to computer
```

Filtering: following Fawcett (2016)
```{r}
#1. Remove trials: more than 50% were bad
poo <- poo3
subs <- unique(poo$subID)
poo$trial.p.missing <- 999
for (j in 1:length(subs)) {
  trials <- unique(poo$TRIAL_INDEX[poo$subID==subs[j]])
  print(j)
for (i in 1:length(trials)) {
  p.missing <- length(which(is.na(poo$PUPIL_CORRECTED[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]])))/length(poo$PUPIL_CORRECTED[poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]])*100
  b <- min(which(poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]))
  bb <- max(which(poo$TRIAL_INDEX==trials[i] & poo$subID==subs[j]))
  poo$trial.p.missing[b:bb] <- p.missing
}}
poo4 <- subset(poo, trial.p.missing < 50) #remove trials with more than 50% missing

#2. Remove outliers - trials more than 2.5 SDs from the mean were removed
subs <- unique(poo4$subID)
poo4$pupilaverage.trial <- 99
#calculate average pupil change for each trial
for (j in 1:length(subs)) {
  trials <- unique(poo4$TRIAL_INDEX[poo4$subID==subs[j]])
  print(j)
for (i in 1:length(trials)) {
  poo4$pupilaverage.trial[poo4$subID==subs[j] & poo4$TRIAL_INDEX==trials[i]] <- mean(poo4$PUPIL_CORRECTED[poo4$subID==subs[j]& poo4$TRIAL_INDEX==trials[i]],na.rm = TRUE)
}}

poo4$outlier <- 0

for (j in 1:length(subs)) {
  trials <- unique(poo4$TRIAL_INDEX[poo4$subID==subs[j]])
  # calculate mean of pupil for one subject
  avg <- mean(poo4$pupilaverage.trial[poo4$subID==subs[j]],na.rm = TRUE)
  # calculate 2.5 SD 
  stdev <- sd(poo4$pupilaverage.trial[poo4$subID==subs[j]],na.rm = TRUE) # one SD
  up.stdev <- avg+(stdev*2.5) #upperbound
  low.stdev <- avg-(stdev*2.5) #lowerbound
  print(j)
for (i in 1:length(trials)) {
  if (poo4$pupilaverage.trial[poo4$subID==subs[j] & poo4$TRIAL_INDEX==trials[i]] > up.stdev) {
    poo4$outlier[poo4$subID==subs[j] & poo4$TRIAL_INDEX==trials[i]] <- 99
  }
  if (poo4$pupilaverage.trial[poo4$subID==subs[j] & poo4$TRIAL_INDEX==trials[i]] < low.stdev) {
    poo4$outlier[poo4$subID==subs[j] & poo4$TRIAL_INDEX==trials[i]] <- 99
  }
}
  #warnings can be ignored
}

unique(poo4$outlier)

#remove outliers
poo5 <- subset(poo4, outlier == 0)

pupil.sub <- ddply(poo5,.(subID,TRIAL_INDEX),summarise,pupilsize=mean(PUPIL_CORRECTED,na.rm = TRUE))

ggplot(pupil.sub,aes(x=factor(subID),y=pupilsize,fill=factor(TRIAL_INDEX),color=factor(TRIAL_INDEX)))+
  theme_bw()+theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line = element_line(colour = "black"))+
  geom_point()+ggtitle("Pupil change per subject (removing trials > 2.5 SD)")+
  labs(x = "Subject", y = "Pupil change (%)")+
  theme(plot.title = element_text(face="bold", size=20, hjust=0))+
  theme(axis.title = element_text(face="bold", size=20))+ 
  theme(axis.text.x  = element_text(size=20),axis.text.y  = element_text(size=20))+
  theme(legend.text=element_text(size=16),legend.title=element_text(size=16))+
  theme(legend.position="none")+
  scale_y_continuous(labels=percent,limits=c(-0.6,1.5),breaks=seq(-0.6,1.5,0.5))

write.csv(poo5, "Pinwheel14_11-17_Infant_Preprocessed_RemovedOutliers.csv", row.names=TRUE) #save to
```
